var mirrorToPath = require('../helpers/path-mirror.js');

var types = mirrorToPath({

  FORECASTING_SET_USER : null,
  FORECASTING_SET_GROUP : null,
  FORECASTING_SET_INTERVAL : null,
  
  FORECASTING_GROUP_CATALOG_REQUEST : null,
  FORECASTING_GROUP_CATALOG_RESPONSE : null,
  FORECASTING_GROUP_CATALOG_FILTER_TYPE : null,
  
  FORECASTING_GROUP_CHART_DATA_REQUEST : null,
  FORECASTING_GROUP_CHART_DATA_RESPONSE : null,

  FORECASTING_USER_DATA_REQUEST : null,
  FORECASTING_USER_DATA_RESPONSE : null,
  
  FORECASTING_ADD_FAVOURITE_REQUEST: null,
  FORECASTING_ADD_FAVOURITE_RESPONSE: null,
  
  USER_RECEIVED_LOGOUT : null

  
});

module.exports = types;
